Repository AY2324S1-CS2103-F13-1/tp, pull requests merged in 2023-10, with the labels that each got.

#94 edit PPP
  docs/team/angelyxx.md
Labels: TODO 1.1

#123 Add functionality for `filter` command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/CompanyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/JobContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/person/CompanyContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/JobContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/tag/TagContainsKeywordsPredicateTest.java
Labels: 1.2

#149 Update DG with implementation of filter and UML diagram changes
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/FilterSequenceDiagram.png
  docs/images/ModelClassDiagram.png
Labels: priority.High
